### PR TITLE
Alex firebase

### PR DESCRIPTION
**Pull request by alexjaegook**

### CODE REVIEW

**Comment by vpalacios9** [comment]
Firebase set up looks great. Add more comments on how Firebase is being used and set up in the Create Queue Page. I also suggest to add //TODO comments for future work that will be required in future sprints regarding this page.

**Review by vpalacios9 — COMMENTED** [review]
Firebase set up looks great. Add more comments on how Firebase is being used and set up in the Create Queue Page. I also suggest to add //TODO comments for future work that will be required in future sprints regarding this page.

**Comment by arhumkhan123** [comment]
LGTM. Like the firebase

**Review by arhumkhan123 — COMMENTED** [review]
LGTM

**Pull request merged**
